modLoader="javafml"
loaderVersion="[${minForgeVersion},)"
license="MIT License"
issueTrackerURL="https://github.com/spectrapulse/${main}/issues"
[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
logoFile="icon.png"
authors="LaidBackSloth, spectrapulse"
description="${description}"
[[dependencies.${id}]]
    modId="forge"
    mandatory=true
    versionRange="[${minForgeVersion},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraftVersion},${nextMinecraftVersion})"
    ordering="NONE"
    side="BOTH"