name: Build
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: gradle/wrapper-validation-action@v3

      - uses: actions/setup-java@v4
        with:
          distribution: adopt-hotspot
          java-version: 17

      - run: chmod +x ./gradlew

      - run: ./gradlew build github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/